In [ ]:
from func import *

# Design matrix

In [2]:
df1 = pd.read_csv(getpath(1), sep = ';') 
df2 = pd.read_csv(getpath(2), sep = ';') 
df3 = pd.read_csv(getpath(3), sep = ';')  
df4 = pd.read_csv(getpath(4)) 
df5 = pd.read_csv(getpath(5), sep = ';') 
df6 = pd.read_csv(getpath(6), sep = ';') 
df7 = pd.read_csv(getpath(7), sep = ';')

In [3]:
## on va concaténer les dataframes
frames = [df1, df2, df3, df4, df5, df6]
df = pd.concat(frames, ignore_index=True)
# df

In [4]:
for i in range(len(df)):
    if df['Name'][i] == 'PADMÉ':
        df.at[i, 'Name'] = 'PADME'
    elif df['Name'][i] == 'AMIDALA':
        df.at[i, 'Name'] = 'PADME'
    elif df['Name'][i] == 'C-3PO':
        df.at[i, 'Name'] = 'THREEPIO'
    elif df['Name'][i] == 'EMPEROR':
        df.at[i, 'Name'] = 'PALPATINE'
    elif df['Name'][i] == 'DARTH SIDIOUS':
        df.at[i, 'Name'] = 'PALPATINE'
    elif df['Name'][i] == 'MACE':
        df.at[i, 'Name'] = 'MACE WINDU'
    elif df['Name'][i] == 'MACE WlNDU':
        df.at[i, 'Name'] = 'MACE WINDU'
    elif df['Name'][i] == 'DARTH SlDIOUS':
        df.at[i, 'Name'] = 'PALPATINE'
    elif df['Name'][i] == 'MACE WiNDU': # add it to M1 file
        df.at[i, 'Name'] = 'MACE WINDU'
    elif df['Name'][i] == 'Kl-ADI-MUNDI': # add it to M1 file
        df.at[i, 'Name'] = 'KI-ADI'
    elif df['Name'][i] == 'BERU': # add it to M1 file
        df.at[i, 'Name'] = 'AUNT BERU'
#     elif df['Name'][i] == 'GOLD LEADER':
#         df.at[i, 'Name'] = 'VADER'

In [5]:
D = design_matrix(df)

In [6]:
Df7 = design_matrix(df7)

In [7]:
D1 = D.sort_values(by=['nb_paroles'], ascending=False, ignore_index=True)

In [8]:
D1.head(30)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots
0,ANAKIN,cleaning bin like angel angel heard deep space...,660,0.120813,2797,0.100742
1,LUKE,hurry come waiting get gear shape guy biggs kn...,474,0.086766,1968,0.070883
2,OBI-WAN,bad feeling mission master something elsewhere...,459,0.084020,2062,0.074269
3,HAN,han solo captain millennium falcon chewie tell...,445,0.081457,2042,0.073548
4,PADME,pleased hear say viceroy trade boycott planet ...,380,0.069559,2074,0.074701
5,THREEPIO,threepio human cyborg relation might serve beg...,356,0.065166,2002,0.072108
6,PALPATINE,could true assurance chancellor ambassaodrs ar...,233,0.042651,1949,0.070199
7,LEIA,lord vader known could bold imperial senate si...,211,0.038623,788,0.028382
8,QUI-GON,captain tell wish board sense anything center ...,200,0.036610,1004,0.036162
9,YODA,republic threatened involved sith hard see dar...,168,0.030752,982,0.035370
10,VADER,transmission intercepted done plan consular sh...,138,0.025261,693,0.024960
11,BEN,hello come little friend afraid worry right re...,107,0.019586,769,0.027698
12,JAR JAR,oh noooooooooo hey help oyi mooie luv yous spa...,106,0.019403,624,0.022475
13,LANDO,slimy double crossing good swindler got lot gu...,98,0.017939,475,0.017108
14,MACE WINDU,sith lord believe could returned without u kno...,86,0.015742,525,0.018909
15,BAIL ORGANA,alderaan second motion vote confidence chancel...,45,0.008237,239,0.008608
16,NUTE,yes coarse ahhh know blockade perfectly legal ...,41,0.007505,213,0.007672
17,WATTO,hi chuba da naga want ah yes nubian lot kinda ...,40,0.007322,291,0.010481
18,SHMI,oh annie anakin oh tank thank much sorry abrup...,36,0.006590,161,0.005799
19,RED LEADER,luke skywalker checked incom sixty five met fa...,34,0.006224,134,0.004826
20,BIGGS,wanted surprise hot shot thought certainly exp...,34,0.006224,246,0.008860
21,CAPT. PANAKA,check transmission generator could federation ...,33,0.006041,174,0.006267
22,OWEN,owen lars guess yourstep brother girlfriend be...,32,0.005858,162,0.005835
23,WEDGE,impossible even computer red two standing look...,32,0.005858,118,0.004250
24,PIETT,admiral think got something sir report fragmen...,31,0.005675,123,0.004430
25,JABBA,welcome mawhonic tuta hok teemto pagalies moon...,29,0.005308,153,0.005511
26,TARKIN,imperial senate longer concern u received word...,28,0.005125,207,0.007456
27,GENERAL GRIEVOUS,situation captain count dooku predicted prepar...,27,0.004942,125,0.004502
28,COUNT DOOKU,senator amidala heard somuch delighted meet at...,27,0.004942,178,0.006411
29,CREATURE,wookiee good eat nothing right chewbacca faste...,25,0.004576,96,0.003458

In [9]:
D7 = Df7.sort_values(by=['nb_paroles'], ascending=False, ignore_index=True)

In [10]:
## char dataframe path
os.path.join(os.getcwd(), '..')
tmp = os.path.abspath(os.path.join(os.getcwd(), '..'))
path = os.path.join(tmp, 'Data', 'Data_Clean', 'characters.csv')

In [11]:
char = pd.read_csv(path, sep = ";")

In [12]:
ll = []
for i in range(len(char)):
    if type(char['gender'][i]) == float or char['gender'][i] == 'none':
        ll.append(i)
char = char.drop(ll)
char.reset_index(drop=True, inplace=True)
# char.head(20)

In [13]:
comun =[]
prenom1 = []
prenom2 = []
for i in range(len(D)):
    for j in range(len(char)):
        for k in D['Name'][i].split():
            if k in char['name'][j].strip().upper().split():
                comun.append((char['name'][j], D['Name'][i]))
                prenom1.append(( char['name'][j]))
                prenom2.append(( D['Name'][i]))
names = unique(comun)

lis = [('BOBA FETT', 'Jango Fett'),
'CAPTAIN ANTILLES', 'Raymus Antilles',
('CAPTAIN ANTILLES', 'Captain Phasma'),
('CAPTAIN PANAKA', 'Captain Phasma'),
('CAPTAIN TYPHO', 'Captain Phasma'),
('HAN and LUKE', 'Luke Skywalker'),
('CLONE CAPTAIN', 'Captain Phasma'),
('DARTH MAUL', 'Darth Vader'),
('DARTH SIDIOUS', 'Darth Vader'),
('DARTH SIDIOUS', 'Darth Maul'),
('DARTH SlDIOUS', 'Darth Vader'),
('DARTH SlDIOUS', 'Darth Maul'),
('DARTH VADER', 'Darth Maul'),
('DROID CAPTAIN', 'Captain Phasma'),
('HAN and LUKE', 'Han Solo'),
('REBEL CAPTAIN', 'Captain Phasma'),
('SHUTTLE CAPTAIN', 'Captain Phasma'),
('PALPATINE is putting on his dark cloak', 'Palpatine')]

new = []
for i in names:
    if i not in lis:
        new.append(i)
dicti = dict(new)
char1 = char.replace({"name": dicti})
char1

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species
0,LUKE,172.0,77,blond,fair,blue,19BBY,male,Tatooine,Human
1,VADER,202.0,136,none,white,yellow,41.9BBY,male,Tatooine,Human
2,LEIA,150.0,49,brown,light,brown,19BBY,female,Alderaan,Human
3,OWEN,178.0,120,"brown, grey",light,blue,52BBY,male,Tatooine,Human
4,BERU,165.0,75,brown,light,blue,47BBY,female,Tatooine,Human
...,...,...,...,...,...,...,...,...,...,...
77,Finn,NaN,NaN,black,dark,dark,NaN,male,NaN,Human
78,Rey,170.0,NaN,brown,light,hazel,NaN,female,NaN,Human
79,Poe Dameron,NaN,NaN,brown,light,brown,NaN,male,NaN,Human
80,SHUTTLE CAPTAIN,NaN,NaN,NaN,NaN,NaN,NaN,female,NaN,NaN
81,PADMÉ,165.0,45,brown,light,brown,46BBY,female,Naboo,Human

In [14]:

D1['gender'] = ""
for i in range(len(D1['Name'])):
    if D1['Name'][i] in list(char1["name"]):
        D1.at[i, 'gender'] = list(char1[char1["name"]==D1['Name'][i]]['gender'])[0]
D1.head(50)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender
0,ANAKIN,cleaning bin like angel angel heard deep space...,660,0.120813,2797,0.100742,male
1,LUKE,hurry come waiting get gear shape guy biggs kn...,474,0.086766,1968,0.070883,male
2,OBI-WAN,bad feeling mission master something elsewhere...,459,0.084020,2062,0.074269,male
3,HAN,han solo captain millennium falcon chewie tell...,445,0.081457,2042,0.073548,
4,PADME,pleased hear say viceroy trade boycott planet ...,380,0.069559,2074,0.074701,
5,THREEPIO,threepio human cyborg relation might serve beg...,356,0.065166,2002,0.072108,
6,PALPATINE,could true assurance chancellor ambassaodrs ar...,233,0.042651,1949,0.070199,
7,LEIA,lord vader known could bold imperial senate si...,211,0.038623,788,0.028382,female
8,QUI-GON,captain tell wish board sense anything center ...,200,0.036610,1004,0.036162,male
9,YODA,republic threatened involved sith hard see dar...,168,0.030752,982,0.035370,male
10,VADER,transmission intercepted done plan consular sh...,138,0.025261,693,0.024960,male
11,BEN,hello come little friend afraid worry right re...,107,0.019586,769,0.027698,male
12,JAR JAR,oh noooooooooo hey help oyi mooie luv yous spa...,106,0.019403,624,0.022475,male
13,LANDO,slimy double crossing good swindler got lot gu...,98,0.017939,475,0.017108,male
14,MACE WINDU,sith lord believe could returned without u kno...,86,0.015742,525,0.018909,
15,BAIL ORGANA,alderaan second motion vote confidence chancel...,45,0.008237,239,0.008608,male
16,NUTE,yes coarse ahhh know blockade perfectly legal ...,41,0.007505,213,0.007672,
17,WATTO,hi chuba da naga want ah yes nubian lot kinda ...,40,0.007322,291,0.010481,male
18,SHMI,oh annie anakin oh tank thank much sorry abrup...,36,0.006590,161,0.005799,female
19,RED LEADER,luke skywalker checked incom sixty five met fa...,34,0.006224,134,0.004826,
20,BIGGS,wanted surprise hot shot thought certainly exp...,34,0.006224,246,0.008860,male
21,CAPT. PANAKA,check transmission generator could federation ...,33,0.006041,174,0.006267,
22,OWEN,owen lars guess yourstep brother girlfriend be...,32,0.005858,162,0.005835,male
23,WEDGE,impossible even computer red two standing look...,32,0.005858,118,0.004250,male
24,PIETT,admiral think got something sir report fragmen...,31,0.005675,123,0.004430,
25,JABBA,welcome mawhonic tuta hok teemto pagalies moon...,29,0.005308,153,0.005511,hermaphrodite
26,TARKIN,imperial senate longer concern u received word...,28,0.005125,207,0.007456,male
27,GENERAL GRIEVOUS,situation captain count dooku predicted prepar...,27,0.004942,125,0.004502,male
28,COUNT DOOKU,senator amidala heard somuch delighted meet at...,27,0.004942,178,0.006411,
29,CREATURE,wookiee good eat nothing right chewbacca faste...,25,0.004576,96,0.003458,
30,TROOPER,set stun right inform lord vader prisoner long...,19,0.003478,57,0.002053,
31,LAMA SU,please trust going enjoyyour stay happy youhav...,19,0.003478,171,0.006159,male
32,BOSS NASS,yousa cannot bee hair dis army mackineeks dare...,17,0.003112,148,0.005331,male
33,JOCASTA NU,call assistance powerful face one mostbrillian...,15,0.002746,146,0.005259,female
34,ACKBAR,see death star orbiting forest moon endor alth...,14,0.002563,106,0.003818,male
35,GOLD LEADER,pardon asking sir good snub fighter going red ...,14,0.002563,48,0.001729,
36,RIC OLIE,communication still jammed power back little d...,14,0.002563,67,0.002413,male
37,RUNE,ever encountered jedi knight sir enough sir su...,14,0.002563,48,0.001729,
38,RIEEKAN,solo commander skywalker reported yet meteor a...,13,0.002380,71,0.002557,
39,KI-ADI,impossible sith extinct millenium sense reveal...,12,0.002197,50,0.001801,
40,OFFICER,station another officer come close outboard sh...,12,0.002197,62,0.002233,
41,MAS AMEDDA,order shall thew supreme chancellor request re...,12,0.002197,65,0.002341,male
42,TAUN WE,welcome tipoca city masterjedi everything read...,11,0.002014,69,0.002485,female
43,DEXTER JETTSTER,obi wan take seat right ya hey ol buddy friend...,11,0.002014,72,0.002593,male
44,PILOT,see anything battery fire reverse stabilizer m...,11,0.002014,33,0.001189,
45,CLONE COMMANDER CODY,fortunately city concentrated small continent ...,10,0.001830,35,0.001261,
46,BOBA FETT,sure dad taun dad dad look dad watch got yeahh...,10,0.001830,21,0.000756,
47,CAPTAIN TYPHO,made guess wrong danger lady still danger vote...,10,0.001830,47,0.001693,male
48,BIBBLE,malfunction communication disruption mean one ...,10,0.001830,69,0.002485,
49,COMMANDER,holding dangerous word get could generate symp...,10,0.001830,38,0.001369,

In [15]:
def add_gender(D,perso, gender):
    D.iloc[D.index[D['Name'] == perso].tolist()[0], 6] = gender
    return 
add_gender(D1, 'HAN', 'male')
add_gender(D1, 'PADME', 'female')
add_gender(D1, 'THREEPIO', 'male') # florent : je l'ai changé
add_gender(D1, 'PALPATINE', 'male')
add_gender(D1, 'MACE WINDU', 'male')
add_gender(D1, 'NUTE', 'male')
add_gender(D1, 'RED LEADER', 'male')
add_gender(D1, 'CAPT. PANAKA', 'male')
add_gender(D1, 'PIETT', 'male')
add_gender(D1, 'COUNT DOOKU', 'male')
add_gender(D1, 'TROOPER', 'male')
add_gender(D1, 'RUNE', 'male')
add_gender(D1, 'RIEEKAN', 'male')
add_gender(D1, 'OFFICER', 'male')
add_gender(D1, 'PILOT', 'male')
add_gender(D1, 'DEXTER JETTSTER', 'male')
add_gender(D1, 'CLONE COMMANDER CODY', 'male')
add_gender(D1, 'BOBA FETT', 'male')
add_gender(D1, 'BIBBLE', 'male')
add_gender(D1, 'QUEEN JAMILLIA', 'female')
# add_gender(D1, '', 'male')
# add_gender(D1, '', 'male')
# add_gender(D1, '', 'male')

add_gender(D1, 'JANGO', 'male')
add_gender(D1, 'AUNT BERU', 'female')
add_gender(D1, 'KI-ADI','male')
add_gender(D1, 'DODONNA','male')
add_gender(D1, 'GOLD LEADER','male')
add_gender(D1, 'DARTH MAUL', 'male')
add_gender(D1, 'JABBA', 'male') # florent : il n'est pas hermaphrodite

In [16]:
D1.head(10)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender
0,ANAKIN,cleaning bin like angel angel heard deep space...,660,0.120813,2797,0.100742,male
1,LUKE,hurry come waiting get gear shape guy biggs kn...,474,0.086766,1968,0.070883,male
2,OBI-WAN,bad feeling mission master something elsewhere...,459,0.084020,2062,0.074269,male
3,HAN,han solo captain millennium falcon chewie tell...,445,0.081457,2042,0.073548,male
4,PADME,pleased hear say viceroy trade boycott planet ...,380,0.069559,2074,0.074701,female
5,THREEPIO,threepio human cyborg relation might serve beg...,356,0.065166,2002,0.072108,male
6,PALPATINE,could true assurance chancellor ambassaodrs ar...,233,0.042651,1949,0.070199,male
7,LEIA,lord vader known could bold imperial senate si...,211,0.038623,788,0.028382,female
8,QUI-GON,captain tell wish board sense anything center ...,200,0.036610,1004,0.036162,male
9,YODA,republic threatened involved sith hard see dar...,168,0.030752,982,0.035370,male

In [17]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer
import os 
import matplotlib.pyplot as plt
from matplotlib.pyplot import hist

In [18]:
## les mots les plus fréqents dans D
liste = []
ll = []
for i in range(len(D.iloc[:, 2])):
    ll.append(D.iloc[:, 1][i].split())

for i in ll:
    for j in i:
        liste.append(j)
all_words = nltk.FreqDist(liste)
# all_words = list(all_words.keys())
all_words

FreqDist({'know': 235, 'master': 235, 'jedi': 232, 'going': 212, 'get': 197, 'right': 189, 'one': 182, 'u': 177, 'see': 175, 'come': 167, ...})

In [19]:
## les mots les plus fréqents dans D
liste1 = []
ll1 = []
for i in range(len(D7.iloc[:, 2])):
    ll1.append(D7.iloc[:, 1][i].split())

for i in ll1:
    for j in i:
        liste1.append(j)
all_words1 = nltk.FreqDist(liste1)
Counter(all_words1).most_common()[1:20]

[('back', 35),
 ('droid', 32),
 ('know', 32),
 ('go', 29),
 ('got', 29),
 ('one', 29),
 ('need', 28),
 ('come', 28),
 ('first', 26),
 ('see', 25),
 ('order', 23),
 ('resistance', 22),
 ('u', 22),
 ('bb', 22),
 ('han', 22),
 ('finn', 21),
 ('good', 21),
 ('solo', 21),
 ('right', 20)]

On tombe donc dans le même problème que précédement, les mots les plus pronencés ne semblent porter aucune information...

## Préparation des matrices de "design"

##### Matrice avec mots de nos choix :

In [20]:
X1 = D1.copy()
for i in range(len(X1)):
    X1.at[i, 'master'] = X1['paroles_traités'][i].split().count('master')
    X1.at[i, 'jedi'] = X1['paroles_traités'][i].split().count('jedi')
    X1.at[i, 'ship'] = X1['paroles_traités'][i].split().count('ship')
    X1.at[i, 'force'] = X1['paroles_traités'][i].split().count('force')
    X1.at[i, 'power'] = X1['paroles_traités'][i].split().count('power')

In [21]:
liste = []
ll = []
for i in range(len(D.iloc[:, 2])):
    ll.append(D.iloc[:, 1][i].split())

for i in ll:
    for j in i:
        liste.append(j)
all_words = nltk.FreqDist(liste)
# all_words = list(all_words.keys())
all_words

word = pd.DataFrame(all_words.items()).sort_values(by=[1], ascending=False, ignore_index=True)
word.head(60)

X1 = D1.copy()
for i in range(len(X1)):
    X1.at[i, 'master'] = X1['paroles_traités'][i].split().count('master') / word.iloc[np.where(word[0]=='master')[0]][1].values
    X1.at[i, 'jedi'] = X1['paroles_traités'][i].split().count('jedi') / word.iloc[np.where(word[0]=='jedi')[0]][1].values
    X1.at[i, 'ship'] = X1['paroles_traités'][i].split().count('ship') / word.iloc[np.where(word[0]=='ship')[0]][1].values
    X1.at[i, 'force'] = X1['paroles_traités'][i].split().count('force') / word.iloc[np.where(word[0]=='force')[0]][1].values
    X1.at[i, 'power'] = X1['paroles_traités'][i].split().count('power') / word.iloc[np.where(word[0]=='power')[0]][1].values
X1.head(10)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender,master,jedi,ship,force,power
0,ANAKIN,cleaning bin like angel angel heard deep space...,660,0.120813,2797,0.100742,male,0.302128,0.189655,0.080645,0.063063,0.101010
1,LUKE,hurry come waiting get gear shape guy biggs kn...,474,0.086766,1968,0.070883,male,0.029787,0.025862,0.032258,0.054054,0.060606
2,OBI-WAN,bad feeling mission master something elsewhere...,459,0.084020,2062,0.074269,male,0.178723,0.077586,0.080645,0.081081,0.060606
3,HAN,han solo captain millennium falcon chewie tell...,445,0.081457,2042,0.073548,male,0.000000,0.004310,0.145161,0.018018,0.070707
4,PADME,pleased hear say viceroy trade boycott planet ...,380,0.069559,2074,0.074701,female,0.017021,0.081897,0.040323,0.009009,0.010101
5,THREEPIO,threepio human cyborg relation might serve beg...,356,0.065166,2002,0.072108,male,0.136170,0.012931,0.040323,0.000000,0.050505
6,PALPATINE,could true assurance chancellor ambassaodrs ar...,233,0.042651,1949,0.070199,male,0.055319,0.181034,0.040323,0.126126,0.161616
7,LEIA,lord vader known could bold imperial senate si...,211,0.038623,788,0.028382,female,0.000000,0.000000,0.032258,0.000000,0.010101
8,QUI-GON,captain tell wish board sense anything center ...,200,0.036610,1004,0.036162,male,0.004255,0.038793,0.072581,0.099099,0.050505
9,YODA,republic threatened involved sith hard see dar...,168,0.030752,982,0.035370,male,0.046809,0.056034,0.016129,0.207207,0.030303

In [22]:
X1 = X1.drop(['nb_paroles', 'nb_mots'], axis = 1)
X1.head(5)

,Name,paroles_traités,perc_parole,perc_mots,gender,master,jedi,ship,force,power
0,ANAKIN,cleaning bin like angel angel heard deep space...,0.120813,0.100742,male,0.302128,0.189655,0.080645,0.063063,0.101010
1,LUKE,hurry come waiting get gear shape guy biggs kn...,0.086766,0.070883,male,0.029787,0.025862,0.032258,0.054054,0.060606
2,OBI-WAN,bad feeling mission master something elsewhere...,0.084020,0.074269,male,0.178723,0.077586,0.080645,0.081081,0.060606
3,HAN,han solo captain millennium falcon chewie tell...,0.081457,0.073548,male,0.000000,0.004310,0.145161,0.018018,0.070707
4,PADME,pleased hear say viceroy trade boycott planet ...,0.069559,0.074701,female,0.017021,0.081897,0.040323,0.009009,0.010101

##### Matrice avec les mots les plus fréquents dans la matrice D

In [23]:
X2 = D1.copy()
for i in range(len(X2)):
    X2.at[i, 'know'] = X2['paroles_traités'][i].split().count('know')
    X2.at[i, 'master'] = X2['paroles_traités'][i].split().count('master')
    X2.at[i, 'jedi'] = X2['paroles_traités'][i].split().count('jedi')
    X2.at[i, 'going'] = X2['paroles_traités'][i].split().count('going')
    X2.at[i, 'get'] = X2['paroles_traités'][i].split().count('get')

In [24]:
liste = []
ll = []
for i in range(len(D.iloc[:, 2])):
    ll.append(D.iloc[:, 1][i].split())

for i in ll:
    for j in i:
        liste.append(j)
all_words = nltk.FreqDist(liste)
# all_words = list(all_words.keys())
all_words

word = pd.DataFrame(all_words.items()).sort_values(by=[1], ascending=False, ignore_index=True)
word.head(60)

X2 = D1.copy()
for i in range(len(X2)):
    X2.at[i, 'know'] = X2['paroles_traités'][i].split().count('know') / word.iloc[np.where(word[0]=='know')[0]][1].values
    X2.at[i, 'master'] = X2['paroles_traités'][i].split().count('master') / word.iloc[np.where(word[0]=='master')[0]][1].values
    X2.at[i, 'jedi'] = X2['paroles_traités'][i].split().count('jedi') / word.iloc[np.where(word[0]=='jedi')[0]][1].values
    X2.at[i, 'going'] = X2['paroles_traités'][i].split().count('going') / word.iloc[np.where(word[0]=='going')[0]][1].values
    X2.at[i, 'get'] = X2['paroles_traités'][i].split().count('get') / word.iloc[np.where(word[0]=='get')[0]][1].values
X2.head(10)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender,know,master,jedi,going,get
0,ANAKIN,cleaning bin like angel angel heard deep space...,660,0.120813,2797,0.100742,male,0.170213,0.302128,0.189655,0.155660,0.096447
1,LUKE,hurry come waiting get gear shape guy biggs kn...,474,0.086766,1968,0.070883,male,0.131915,0.029787,0.025862,0.141509,0.126904
2,OBI-WAN,bad feeling mission master something elsewhere...,459,0.084020,2062,0.074269,male,0.068085,0.178723,0.077586,0.080189,0.081218
3,HAN,han solo captain millennium falcon chewie tell...,445,0.081457,2042,0.073548,male,0.085106,0.000000,0.004310,0.160377,0.228426
4,PADME,pleased hear say viceroy trade boycott planet ...,380,0.069559,2074,0.074701,female,0.085106,0.017021,0.081897,0.075472,0.030457
5,THREEPIO,threepio human cyborg relation might serve beg...,356,0.065166,2002,0.072108,male,0.072340,0.136170,0.012931,0.113208,0.055838
6,PALPATINE,could true assurance chancellor ambassaodrs ar...,233,0.042651,1949,0.070199,male,0.063830,0.055319,0.181034,0.033019,0.025381
7,LEIA,lord vader known could bold imperial senate si...,211,0.038623,788,0.028382,female,0.068085,0.000000,0.000000,0.037736,0.065990
8,QUI-GON,captain tell wish board sense anything center ...,200,0.036610,1004,0.036162,male,0.025532,0.004255,0.038793,0.014151,0.050761
9,YODA,republic threatened involved sith hard see dar...,168,0.030752,982,0.035370,male,0.021277,0.046809,0.056034,0.000000,0.000000

In [25]:
X2 = X2.drop(['nb_paroles', 'nb_mots'], axis = 1)
X2.head(5)

,Name,paroles_traités,perc_parole,perc_mots,gender,know,master,jedi,going,get
0,ANAKIN,cleaning bin like angel angel heard deep space...,0.120813,0.100742,male,0.170213,0.302128,0.189655,0.155660,0.096447
1,LUKE,hurry come waiting get gear shape guy biggs kn...,0.086766,0.070883,male,0.131915,0.029787,0.025862,0.141509,0.126904
2,OBI-WAN,bad feeling mission master something elsewhere...,0.084020,0.074269,male,0.068085,0.178723,0.077586,0.080189,0.081218
3,HAN,han solo captain millennium falcon chewie tell...,0.081457,0.073548,male,0.085106,0.000000,0.004310,0.160377,0.228426
4,PADME,pleased hear say viceroy trade boycott planet ...,0.069559,0.074701,female,0.085106,0.017021,0.081897,0.075472,0.030457

##### Matrice avec les mots les plus fréquents dans la matrice D7 (dernière épisode)

In [26]:
X5 = D1.copy()
for i in range(len(X5)):
    X5.at[i, 'get'] = X5['paroles_traités'][i].split().count('get')
    X5.at[i, 'back'] = X5['paroles_traités'][i].split().count('back')
    X5.at[i, 'droid'] = X5['paroles_traités'][i].split().count('droid')
    X5.at[i, 'know'] = X5['paroles_traités'][i].split().count('know')
    X5.at[i, 'go'] = X5['paroles_traités'][i].split().count('go')

In [27]:
liste = []
ll = []
for i in range(len(D.iloc[:, 2])):
    ll.append(D.iloc[:, 1][i].split())

for i in ll:
    for j in i:
        liste.append(j)
all_words = nltk.FreqDist(liste)
# all_words = list(all_words.keys())
all_words

word = pd.DataFrame(all_words.items()).sort_values(by=[1], ascending=False, ignore_index=True)
word.head(60)

X5 = D1.copy()
for i in range(len(X5)):
    X5.at[i, 'get'] = X5['paroles_traités'][i].split().count('get') / word.iloc[np.where(word[0]=='get')[0]][1].values
    X5.at[i, 'back'] = X5['paroles_traités'][i].split().count('back') / word.iloc[np.where(word[0]=='back')[0]][1].values
    X5.at[i, 'droid'] = X5['paroles_traités'][i].split().count('droid') / word.iloc[np.where(word[0]=='droid')[0]][1].values
    X5.at[i, 'know'] = X5['paroles_traités'][i].split().count('know') / word.iloc[np.where(word[0]=='know')[0]][1].values
    X5.at[i, 'go'] = X5['paroles_traités'][i].split().count('go') / word.iloc[np.where(word[0]=='go')[0]][1].values
X5.head(10)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender,get,back,droid,know,go
0,ANAKIN,cleaning bin like angel angel heard deep space...,660,0.120813,2797,0.100742,male,0.096447,0.056911,0.130435,0.170213,0.125786
1,LUKE,hurry come waiting get gear shape guy biggs kn...,474,0.086766,1968,0.070883,male,0.126904,0.178862,0.130435,0.131915,0.119497
2,OBI-WAN,bad feeling mission master something elsewhere...,459,0.084020,2062,0.074269,male,0.081218,0.056911,0.108696,0.068085,0.069182
3,HAN,han solo captain millennium falcon chewie tell...,445,0.081457,2042,0.073548,male,0.228426,0.130081,0.021739,0.085106,0.106918
4,PADME,pleased hear say viceroy trade boycott planet ...,380,0.069559,2074,0.074701,female,0.030457,0.089431,0.086957,0.085106,0.050314
5,THREEPIO,threepio human cyborg relation might serve beg...,356,0.065166,2002,0.072108,male,0.055838,0.097561,0.065217,0.072340,0.075472
6,PALPATINE,could true assurance chancellor ambassaodrs ar...,233,0.042651,1949,0.070199,male,0.025381,0.032520,0.043478,0.063830,0.044025
7,LEIA,lord vader known could bold imperial senate si...,211,0.038623,788,0.028382,female,0.065990,0.024390,0.043478,0.068085,0.037736
8,QUI-GON,captain tell wish board sense anything center ...,200,0.036610,1004,0.036162,male,0.050761,0.032520,0.065217,0.025532,0.056604
9,YODA,republic threatened involved sith hard see dar...,168,0.030752,982,0.035370,male,0.000000,0.016260,0.021739,0.021277,0.044025

In [28]:
X5 = X5.drop(['nb_paroles', 'nb_mots'], axis = 1)
X5.head(5)

,Name,paroles_traités,perc_parole,perc_mots,gender,get,back,droid,know,go
0,ANAKIN,cleaning bin like angel angel heard deep space...,0.120813,0.100742,male,0.096447,0.056911,0.130435,0.170213,0.125786
1,LUKE,hurry come waiting get gear shape guy biggs kn...,0.086766,0.070883,male,0.126904,0.178862,0.130435,0.131915,0.119497
2,OBI-WAN,bad feeling mission master something elsewhere...,0.084020,0.074269,male,0.081218,0.056911,0.108696,0.068085,0.069182
3,HAN,han solo captain millennium falcon chewie tell...,0.081457,0.073548,male,0.228426,0.130081,0.021739,0.085106,0.106918
4,PADME,pleased hear say viceroy trade boycott planet ...,0.069559,0.074701,female,0.030457,0.089431,0.086957,0.085106,0.050314

In [29]:
X1 = X1[X1.gender != 'hermaphrodite']
X1.reset_index(drop=True, inplace=True)
# X1 = X1[X1.nb_paroles >= 10]
# X2 = X2[X2.nb_paroles >= 10]

In [30]:
X2 = X2[X2.gender != 'hermaphrodite']
X2.reset_index(drop=True, inplace=True)
# X2 = X2[X2.nb_paroles >= 10]
# X2.head(50)

In [31]:
## saving the data frame so we can load it elsewhere
os.path.join(os.getcwd(), '..')
tmp1 = os.path.abspath(os.path.join(os.getcwd(), '..'))
path = os.path.join(tmp1, 'Data', 'Design matrix', 'Design_matrix_1.csv')

# X1.to_csv(path, index=False)

In [32]:
## saving the data frame so we can load it elsewhere
os.path.join(os.getcwd(), '..')
tmp1 = os.path.abspath(os.path.join(os.getcwd(), '..'))
path = os.path.join(tmp1, 'Data', 'Design matrix', 'Design_matrix_2.csv')

# X2.to_csv(path, index=False)

##### Préparion de la matrice D7 (dernière épisode)

In [33]:
D7.head(5)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots
0,FINN,yes captain sorry captain rescue helping escap...,163,0.206853,547,0.172392
1,REY,tal ama parqual parqual zatana noma shhhh teed...,145,0.184010,461,0.145288
2,HAN,chewie home others pilot thing understand watc...,137,0.173858,574,0.180901
3,POE,well chance general long time got company hide...,61,0.077411,287,0.090451
4,KYLO REN,look old become know come map skywalker know f...,59,0.074873,244,0.076899

In [34]:
D7['gender'] = ""
D7.head(5)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender
0,FINN,yes captain sorry captain rescue helping escap...,163,0.206853,547,0.172392,
1,REY,tal ama parqual parqual zatana noma shhhh teed...,145,0.184010,461,0.145288,
2,HAN,chewie home others pilot thing understand watc...,137,0.173858,574,0.180901,
3,POE,well chance general long time got company hide...,61,0.077411,287,0.090451,
4,KYLO REN,look old become know come map skywalker know f...,59,0.074873,244,0.076899,

In [35]:
add_gender(D7,'FINN', 'male')
add_gender(D7,'REY', 'female')
add_gender(D7,'HAN', 'male')
add_gender(D7,'POE', 'male')
add_gender(D7,'KYLO REN', 'male')
add_gender(D7,'GENERAL HUX', 'male')
add_gender(D7,'LEIA', 'female')
add_gender(D7,'MAZ', 'female')
add_gender(D7,'SNOKE', 'male')
add_gender(D7,'C-3PO', 'male')

In [36]:
D7.head(5)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender
0,FINN,yes captain sorry captain rescue helping escap...,163,0.206853,547,0.172392,male
1,REY,tal ama parqual parqual zatana noma shhhh teed...,145,0.184010,461,0.145288,female
2,HAN,chewie home others pilot thing understand watc...,137,0.173858,574,0.180901,male
3,POE,well chance general long time got company hide...,61,0.077411,287,0.090451,male
4,KYLO REN,look old become know come map skywalker know f...,59,0.074873,244,0.076899,male

In [37]:
X3 = D7.copy()
for i in range(len(X3)):
    X3.at[i, 'get'] = X3['paroles_traités'][i].split().count('get')
    X3.at[i, 'back'] = X3['paroles_traités'][i].split().count('back')
    X3.at[i, 'droid'] = X3['paroles_traités'][i].split().count('droid')
    X3.at[i, 'know'] = X3['paroles_traités'][i].split().count('know')
    X3.at[i, 'go'] = X3['paroles_traités'][i].split().count('go')

In [38]:
liste = []
ll = []
for i in range(len(D7.iloc[:, 2])):
    ll.append(D7.iloc[:, 1][i].split())

for i in ll:
    for j in i:
        liste.append(j)
all_words7 = nltk.FreqDist(liste)


word7 = pd.DataFrame(all_words7.items()).sort_values(by=[1], ascending=False, ignore_index=True)
word7.head(60)

X3 = D7.copy()
for i in range(len(X3)):
    X3.at[i, 'master'] = X3['paroles_traités'][i].split().count('master') / word7.iloc[np.where(word7[0]=='master')[0]][1].values
    X3.at[i, 'jedi'] = X3['paroles_traités'][i].split().count('jedi') / word7.iloc[np.where(word7[0]=='jedi')[0]][1].values
    X3.at[i, 'ship'] = X3['paroles_traités'][i].split().count('ship') / word7.iloc[np.where(word7[0]=='ship')[0]][1].values
    X3.at[i, 'force'] = X3['paroles_traités'][i].split().count('force') / word7.iloc[np.where(word7[0]=='force')[0]][1].values
    X3.at[i, 'power'] = X3['paroles_traités'][i].split().count('power') / word7.iloc[np.where(word7[0]=='power')[0]][1].values
X3.head(10)

,Name,paroles_traités,nb_paroles,perc_parole,nb_mots,perc_mots,gender,master,jedi,ship,force,power
0,FINN,yes captain sorry captain rescue helping escap...,163,0.206853,547,0.172392,male,0.0,0.000,0.083333,0.111111,0.111111
1,REY,tal ama parqual parqual zatana noma shhhh teed...,145,0.184010,461,0.145288,female,0.2,0.125,0.333333,0.111111,0.111111
2,HAN,chewie home others pilot thing understand watc...,137,0.173858,574,0.180901,male,0.0,0.375,0.250000,0.222222,0.222222
3,POE,well chance general long time got company hide...,61,0.077411,287,0.090451,male,0.0,0.000,0.083333,0.000000,0.000000
4,KYLO REN,look old become know come map skywalker know f...,59,0.074873,244,0.076899,male,0.0,0.000,0.083333,0.222222,0.222222
5,GENERAL HUX,well jakku soon use ventral cannon yes help on...,26,0.032995,147,0.046328,male,0.0,0.000,0.083333,0.000000,0.000000
6,LEIA,jacket need talk incredibly brave renouncing f...,24,0.030457,97,0.030570,female,0.0,0.125,0.000000,0.111111,0.000000
7,MAZ,han solo boyfriend like wookiee assume need so...,19,0.024112,128,0.040340,female,0.0,0.125,0.000000,0.111111,0.000000
8,SNOKE,droid soon delivered resistance leading last j...,14,0.017766,63,0.019855,male,0.2,0.125,0.000000,0.000000,0.000000
9,C-3PO,goodness han solo see threepio probably recogn...,14,0.017766,125,0.039395,male,0.6,0.000,0.000000,0.000000,0.111111

In [39]:
X3 = X3.drop(['nb_paroles', 'nb_mots'], axis = 1)
X3.head(5)

,Name,paroles_traités,perc_parole,perc_mots,gender,master,jedi,ship,force,power
0,FINN,yes captain sorry captain rescue helping escap...,0.206853,0.172392,male,0.0,0.000,0.083333,0.111111,0.111111
1,REY,tal ama parqual parqual zatana noma shhhh teed...,0.184010,0.145288,female,0.2,0.125,0.333333,0.111111,0.111111
2,HAN,chewie home others pilot thing understand watc...,0.173858,0.180901,male,0.0,0.375,0.250000,0.222222,0.222222
3,POE,well chance general long time got company hide...,0.077411,0.090451,male,0.0,0.000,0.083333,0.000000,0.000000
4,KYLO REN,look old become know come map skywalker know f...,0.074873,0.076899,male,0.0,0.000,0.083333,0.222222,0.222222

# Logistic regression

In [40]:
# import model and matrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, RepeatedStratifiedKFold, StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix,roc_curve, roc_auc_score, precision_score, recall_score, precision_recall_curve
from sklearn.metrics import f1_score

In [41]:
#G['gender'][0] == 0

NameError: name 'G' is not defined

In [42]:
import math
def recode(D):
    for i in range(len(D)):
        if G['gender'][i] == 'male':
            D.iloc[i, 4] = 0
        elif G['gender'][i] == 'female':
            D.iloc[i, 4] = 1
        else:
            D.drop(i)

In [44]:
G = X5.copy()
G

,Name,paroles_traités,perc_parole,perc_mots,gender,get,back,droid,know,go
0,ANAKIN,cleaning bin like angel angel heard deep space...,0.120813,0.100742,male,0.096447,0.056911,0.130435,0.170213,0.125786
1,LUKE,hurry come waiting get gear shape guy biggs kn...,0.086766,0.070883,male,0.126904,0.178862,0.130435,0.131915,0.119497
2,OBI-WAN,bad feeling mission master something elsewhere...,0.084020,0.074269,male,0.081218,0.056911,0.108696,0.068085,0.069182
3,HAN,han solo captain millennium falcon chewie tell...,0.081457,0.073548,male,0.228426,0.130081,0.021739,0.085106,0.106918
4,PADME,pleased hear say viceroy trade boycott planet ...,0.069559,0.074701,female,0.030457,0.089431,0.086957,0.085106,0.050314
...,...,...,...,...,...,...,...,...,...,...
284,PILOTS,right okay,0.000183,0.000072,,0.000000,0.000000,0.000000,0.000000,0.000000
285,PILOT VOICE,part technical crew forest moon,0.000183,0.000180,,0.000000,0.000000,0.000000,0.000000,0.000000
286,PILOT #2,get,0.000183,0.000036,,0.005076,0.000000,0.000000,0.000000,0.000000
287,BOBA,dad,0.000183,0.000036,,0.000000,0.000000,0.000000,0.000000,0.000000
288,PALAPATINE,distracted afraid help,0.000183,0.000108,,0.000000,0.000000,0.000000,0.000000,0.000000

In [45]:
## préparation de la matrice X1
def prep_plus_frequentss_D(G):
    recode(G)
    G = G[['perc_parole','perc_mots', 'gender', 'get', 'back', 'droid', 'know', 'go']]
    return G

## préparation de la matrice X2
def prep_plus_frequentss_choice(G):
    recode(G)    
    G = G[['perc_parole','perc_mots', 'gender', 'get', 'back', 'droid', 'know', 'go']]
    return G

## préparation de la matrice X5
def prep_plus_frequents_D7(G):
    recode(G)
    G = G[['perc_parole','perc_mots', 'gender', 'get', 'back', 'droid', 'know', 'go']]
    return G

Nous allons appliquer la régression sur le modèle X5, avec les mots les plus fréquents dans la matrice D7.

In [46]:
G = X5.copy()
G = prep_plus_frequents_D7(G)
G

,perc_parole,perc_mots,gender,get,back,droid,know,go
0,0.120813,0.100742,0,0.096447,0.056911,0.130435,0.170213,0.125786
1,0.086766,0.070883,0,0.126904,0.178862,0.130435,0.131915,0.119497
2,0.084020,0.074269,0,0.081218,0.056911,0.108696,0.068085,0.069182
3,0.081457,0.073548,0,0.228426,0.130081,0.021739,0.085106,0.106918
4,0.069559,0.074701,1,0.030457,0.089431,0.086957,0.085106,0.050314
...,...,...,...,...,...,...,...,...
284,0.000183,0.000072,,0.000000,0.000000,0.000000,0.000000,0.000000
285,0.000183,0.000180,,0.000000,0.000000,0.000000,0.000000,0.000000
286,0.000183,0.000036,,0.005076,0.000000,0.000000,0.000000,0.000000
287,0.000183,0.000036,,0.000000,0.000000,0.000000,0.000000,0.000000
288,0.000183,0.000108,,0.000000,0.000000,0.000000,0.000000,0.000000

##### Application de la régression logistique par défault :

In [48]:
# train test split
X_train, X_test, Y_train, Y_test = train_test_split(G.drop('gender', axis = 1).to_numpy(), G['gender'].to_numpy())

## trainig the model using training data
lg1 = LogisticRegression(fit_intercept = False, penalty = 'none')
lg1.fit(X_train, Y_train)

TypeError: '<' not supported between instances of 'int' and 'str'

In [ ]:
lg1.score(X_test, Y_test)

In [ ]:
Y_pred = lg1.predict(X_test)

In [ ]:
print(f'Accuracy Score: {accuracy_score(Y_test,Y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(Y_test, Y_pred)}')
print(f'Area Under Curve: {roc_auc_score(Y_test, Y_pred)}')
print(f'Recall score: {recall_score(Y_test,Y_pred)}')

On voit donc que notre modèle prédit mal la classe des femmes, même si le score est de 94%, on peut donc compter sur le score comme le seul indicateur de l'efficacité de notre modèle.. fin, il n'a réussi à prédire aucun individu de type 'female'.. bon c'est normale car si on regard l'echantillon d'apprentissage on trouve ça :

In [ ]:
from collections import Counter
Counter(Y_test)

ce qui montre que la proportion des female dans l'échantillon d'apprentissage est égale à 0.03669724770642202. C'est donc très peu....

Pour résoudre ce problème, nous proposons deux approches :

# Resampling
Deux type : le oversampling et le undersampling :

##### Application de la régression logistique avec la technique du "Oversampling"
cette méthode consiste à ajouter des copies de la classe qui est peu existante dans notre jeu de données.

In [ ]:
from sklearn.utils import resample

In [ ]:
G = X5.copy()
G = prep_plus_frequents_D7(G)
G

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(G.drop('gender', axis = 1), G['gender'])

M = pd.concat([X_train, Y_train], axis=1)

male = M[M.gender==0]
female = M[M.gender==1]

female_upsampled = resample(female,
                          replace=True, # sample with replacement
                          n_samples=len(male), # match number in majority class
                          random_state=27)

upsampled = pd.concat([male, female_upsampled])

In [ ]:
upsampled.gender.value_counts()

Rappliquons notre regression logistique :

In [ ]:
Y_train = upsampled.gender
X_train = upsampled.drop('gender', axis=1)

In [ ]:
upsampled = LogisticRegression(class_weight=w, fit_intercept = False, penalty = 'none').fit(X_train, Y_train)

In [ ]:
upsampled_pred = upsampled.predict(X_test)

In [ ]:
print(f'Accuracy Score: {accuracy_score(Y_test,upsampled_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(Y_test, upsampled_pred)}')
print(f'Area Under Curve: {roc_auc_score(Y_test, upsampled_pred)}')
print(f'Recall score: {recall_score(Y_test,upsampled_pred)}')

Le modèle fait trop d'erreur pour la prédiction des hommes

In [ ]:
upsampled.predict(np.array([[ 0.18401, 0.145288, 6.0, 1.0, 1.0, 4.0, 12.0]]))

# Weighted Logistic Regression
Cette methode consiste à associer des poids à la chaque classe afin de ratrapper un peu le manque d'une classe

In [ ]:
x1 = Counter(G['gender'])[0]/(Counter(G['gender'])[1]+Counter(G['gender'])[0])
x2 = Counter(G['gender'])[1]/(Counter(G['gender'])[1]+Counter(G['gender'])[0])

In [ ]:
print('Le pourcentage des hommes dans nos données est :', x1)
print('Le pourcentage des femmes dans nos données est :', x2)

In [ ]:
## dictionnaire des poids
w = {0 : Counter(G['gender'])[1]/(Counter(G['gender'])[1]+Counter(G['gender'])[0]),
    1 : Counter(G['gender'])[0]/(Counter(G['gender'])[1]+Counter(G['gender'])[0])}

In [ ]:
w

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(G.drop('gender', axis = 1), G['gender'])

In [ ]:
lg2 = LogisticRegression(class_weight=w, fit_intercept = False, penalty = 'none')
lg2.fit(X_train, Y_train)

In [ ]:
Y_pred = lg2.predict(X_test)

In [ ]:
# performance
print(f'Accuracy Score: {accuracy_score(Y_test,Y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(Y_test, Y_pred)}')
print(f'Area Under Curve: {roc_auc_score(Y_test, Y_pred)}')
print(f'Recall score: {recall_score(Y_test,Y_pred)}')

On a toujours du mal à prédire la classe des femmes !!!! après faudra peut être penser à prondre qu'une portion de la matrice du design..

##### Application sur REY :

In [ ]:
lg2.predict(np.array([[ 0.18401, 0.145288, 6.0, 1.0, 1.0, 4.0, 12.0]]))

Ca prédit que Rey est un homme, ce qui est faux !!

##### stratified k-fold

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
G = X5.copy()
G = prep_plus_frequents_D7(G)
G

In [ ]:
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)

In [ ]:
X, y = G.drop('gender', axis = 1), G['gender']
for train_ix, test_ix in kfold.split(X, y):
    # select rows
    train_X, test_X = X.iloc[train_ix], X.iloc[test_ix]
    train_y, test_y = y.iloc[train_ix], y.iloc[test_ix]

In [ ]:
lg3 = LogisticRegression(fit_intercept = False, penalty = 'none')
lg3.fit(train_X, train_y)

In [ ]:
lg3.score(test_X, test_y)

In [ ]:
Y_pred = lg3.predict(test_X)

In [ ]:
print(f'Accuracy Score: {accuracy_score(test_y,Y_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(test_y, Y_pred)}')
print(f'Area Under Curve: {roc_auc_score(test_y, Y_pred)}')
print(f'Recall score: {recall_score(test_y,Y_pred)}')

##### Application Sur Rey

In [ ]:
lg3.predict(np.array([[ 0.18401, 0.145288, 6.0, 1.0, 1.0, 4.0, 12.0]]))

Ca prédit que Rey est un homme, ce qui est faux !!

##### Application sur les 10 première lignes

In [ ]:
M = X3.head(10).copy()
M

In [ ]:
M['gender'] = pd.get_dummies(M['gender'], drop_first = False)
M = M[['perc_parole','perc_mots', 'gender', 'get', 'back', 'droid', 'know', 'go']]

In [ ]:
M

In [ ]:
M_test = M['gender']
M_test

In [ ]:
M_pred = lg3.predict(M.drop('gender', axis = 1))

In [ ]:
print(f'Accuracy Score: {accuracy_score(M_test,M_pred)}')
print(f'Confusion Matrix: \n{confusion_matrix(M_test, M_pred)}')
print(f'Area Under Curve: {roc_auc_score(M_test, M_pred)}')
print(f'Recall score: {recall_score(M_test,M_pred)}')

Il a tout classifier comme des hommes !!!